
springdoc:
  swagger-ui:
    path: swagger-ui.html


spring:
  h2 :
    console:
      enabled: true
      path: /h2-console
  profiles:
    active:
      - default
  data:
    rest:
      base-path: /
  datasource:
    url : jdbc:h2:mem:devtaehyeok
    driverClassName: org.h2.Driver
    username: devtaehyeok
    passsword:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect